### ISSUE TITLE
ical_properties dataset - as list

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/ical#2]
I created the dataset `ic_properties` to show properties (equivalent of keys in key-value pairs) allowed (I think this is all of them):

``` r
ical::ic_properties
#>  [1] "CALSCALE"     "METHOD"       "PRODID"       "VERSION"     
#>  [5] "ATTACH"       "CATEGORIES"   "CLASS"        "COMMENT"     
#>  [9] "DESCRIPTION"  "GEO"          "LOCATION"     "PERCENT"     
#> [13] "PRIORITY"     "RESOURCES"    "STATUS"       "SUMMARY"     
#> [17] "COMPLETED"    "DTEND"        "DUE"          "DTSTART"     
#> [21] "DURATION"     "FREEBUSY"     "TRANSP"       "TZID"        
#> [25] "TZNAME"       "TZOFFSETFROM" "TZOFFSETTO"   "TZURL"       
#> [29] "ATTENDEE"     "CONTACT"      "ORGANIZER"    "RECURRENCE"  
#> [33] "RELATED"      "URL"          "UID"          "EXDATE"      
#> [37] "RDATE"        "RRULE"        "ACTION"       "REPEAT"      
#> [41] "TRIGGER"      "CREATED"      "DTSTAMP"      "LAST"        
#> [45] "SEQUENCE"     "REQUEST"      "FLOAT"        "INTEGER"     
#> [49] "AUDIO"        "DISPLAY"      "EMAIL"        "PUBLIC"      
#> [53] "PRIVATE"      "CONFIDENTIAL"
```

Created on 2018-08-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I think to make the 'key keys' easier we should create a named list, a bit like `leaflet::providers` which provides very useful auto-completion options illustrated below:

![image](https://user-images.githubusercontent.com/1825120/43990607-69d50f0c-9d55-11e8-861a-84c17a88120b.png)

**Comment by Robinlovelace** [comment]
Update: I think I've found the 'core' properties of events - see here: https://github.com/ATFutures/ical/commit/9528bdffdc0ddbc0a06460495fb7782f4f066e15

**Comment by layik** [comment]
devtools::install_github("gadenbuie/regexplain")

**Comment by Robinlovelace** [comment]
@layik I saw you had a version of this dataset. Just checked and... happy to say it works!

![image](https://user-images.githubusercontent.com/1825120/44003632-90c4c4ec-9e4d-11e8-9a57-199b80c62f8e.png)

Great fix!

**Comment by Robinlovelace** [comment]
I think only the commonly used 'core properties' benefit from being a named list, so keeping `ic_properties` unchanged.
