### ISSUE TITLE
Function to convert ical datetime format into R datetime class

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/ical#3]
I've created a placeholder - just needs filling in but clear what to do next - see `ic_extract.R`:

```r
#' Convert ical datetime into R datetime
#'
#' @inheritParams ic_find
#'
#' @export
#' @examples
#' ic_datetime("20180809T160000Z")
ic_datetime <- function(x) {

  # todo: return a datetime object

}
```

**Comment by layik** [comment]
Above push is based on the premise that iCal time zone is defined separately.

**Comment by layik** [comment]
That is ‘TZID’ otherwise parsing needs to take into account the training Zone ID (if so)

https://www.kanzaki.com/docs/ical/tzid.html

**Comment by Robinlovelace** [comment]
Fantastic. We can always open more specific issues related to timezones and other edge cases that will likely need more `if()` statements of the type you added in that last commit. Awesome work!
