### ISSUE TITLE
Enable and test round trip I/O

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/ical#7]
Requires `ic_write()` but when we have that and metadata supported eventually we should be able to do something like:

```r
library(ical)
cal = ic_read(system.file("extdata", "england-and-wales.ics", package = "ical"))
ic_write(cal, "cal.ics")
identical(cal, readLines("cal.ics"))
```

Which returns `TRUE` - an ideal use case for testthat.

**Comment by Robinlovelace** [comment]
@layik currently my 'tests' are in the examples. May be worth moving them into the tests. Any ideas/commits on that welcome! More importantly: any ideas how to get round the issue with the funny attribute names in the example illustrated above?

In any case I think this is almost ready to launch: we have a simple `ical` class based on the `tibble` and can do round-trip data I/0 with simple .isc file -> `ical` object -> .isc file!

**Comment by layik** [comment]
Hey! So good to hear.
For the tests, would love to contribute, do give me sometime to get my head round the code and will contribute!

**Comment by Robinlovelace** [comment]
Great. Feel free to have a look whenever, otherwise add it to the list of things for the Thursday minihack!

**Comment by layik** [comment]
So this is related to #15. I think the upcoming commit sorts that too.

**Comment by layik** [comment]
``` r
f <- system.file("extdata", "england-and-wales.ics", package = "ical")
ics_df <- ical::ic_read(f)
ical::ic_write(ics_df, "ic.ics")
identical(ics_df, ical::ic_read("ic.ics"))
#> [1] TRUE
```

Created on 2018-09-23 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

💯 @Robinlovelace

**Comment by Robinlovelace** [comment]
The problem with that is that the useful date class is lost. But definite step in the right direction!

**Comment by layik** [comment]
It was a late night [comment](https://github.com/ATFutures/ical/issues/7#issuecomment-423851678) that one. Sorry @Robinlovelace, what is missing? :) I know I am falling behind here.

**Comment by Robinlovelace** [comment]
Testing round trip on other calanders is missing. It definitely does not work on my work calendar (dates are messed up in addition to the round-trip-issue):

```r
# Aim: load and explore calendar
# Note: ical's support for times needs to be improved!
library(dplyr)
library(ical)
u = "https://outlook.office365.com/owa/calendar/63f6c4e85d124df6a20656ade8e71faa@leeds.ac.uk/32e1cb4137f4414b8d7644453ec4b10414316826143036893453/calendar.ics"
download.file(u, "u.ics")
ical = ical::ic_read("u.ics")
ical::ic_write(ical, "u2.ics")
identical(readLines("u.ics"), readLines("u2.ics"))

# in bash
meld u.ics u2.ics
```


Getting close though:

![image](https://user-images.githubusercontent.com/1825120/45947055-c1d4c780-bfea-11e8-85de-b352236a022d.png)

**Comment by layik** [comment]
Thank you. Should have tried, I just tested again with the extdata within the package. Looking into it.

**Comment by layik** [comment]
Indeed, very close @Robinlovelace, what I can (now) see from my your sleek "meld" above and my Outlook file is this:
1. Description is clipped for some reason, easy to fix.
2. Two extra DTSTART and DTEND's are introduced. Is the main issue?
3. The bits with Microsoft also removed, I know important but perhaps easier to fix
4. Highlighted RED are identical (hence our identical test cases)

![image](https://user-images.githubusercontent.com/408568/45950409-94424b00-bff7-11e8-94ab-670df256e9fd.png)

Am I right?
Can you see anything else?

**Comment by Robinlovelace** [comment]
Great testing @layik no that sounds like a good summary to me. I discovered the issue with multiple lines and couldn't think of a fix. We could say that's unsuported atm but if you have ideas for a fix: amazing! Yes the DTEND should be replaced by the DTEND with additional attributes. I don't think the X-MICROSOFT bits matter: they're add-ons. But could be a bonus if they do work.

In summary: you're right, cannot see anything else right now.

**Comment by layik** [comment]
Fire alarm at Worsley reading on smartphone. Note to self/future. Those MS props are standard. 

https://msdn.microsoft.com/en-us/library/ee178325(v=exchg.80).aspx

**Comment by layik** [comment]
I take back those "easy" words :)

**Comment by layik** [comment]
<img width="1673" alt="screen shot 2018-09-24 at 22 45 21" src="https://user-images.githubusercontent.com/408568/45981110-d5644a80-c04b-11e8-9d39-804917aca8a3.png">

**Comment by Robinlovelace** [comment]
Very impressive.

**Comment by layik** [comment]
``` r
ical <- ical::ic_read("/Users/layik/code/ical/l.ics")
ical::ic_write(ical, "/Users/layik/code/ical/l2.ics")
ll <- readLines("/Users/layik/code/ical/l.ics")
ll2 <- readLines("/Users/layik/code/ical/l2.ics")
identical(ll,ll2)
#> [1] FALSE
length(ll)
#> [1] 552
length(ll2)
#> [1] 582
```

Created on 2018-09-24 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

Removing those extra start/ends should give us the final result.

**Comment by layik** [comment]
So trying to sort that (2) main issue now.

**Comment by layik** [comment]
Right, the "insertion" happens [here](https://github.com/ATFutures/ical/blob/master/R/ic_dataframe.R#L65). 

1. It really isn't an insertion, when we try to one set of "unique" properties for each VEVENT, we need to collate GMT with Greenwich Mean Time as one value. But a unique function on strings cannot do that. 

2. My understanding is that this is NOT a "variable length named vectors". It could be, but it isn't? Why, I am not quite sure :)

So either we find a fix for 1 or we rewrite the function and deal with it at (2).

Might need your help here @Robinlovelace. More like converting named vector list to data frame issue than something else.

**Comment by layik** [comment]
Questions @Robinlovelace: 
1. do all VEVENTS in a VCALENDAR are all in the same TZID?
2. should/must all VEVENTS have the same properties?

Then I can look at the appropriate solution. This thread is doing a good doc job too.

**Comment by layik** [comment]
> remove lines containing NAs

should not happen, looking at upstream always keeps the stream clean.

**Comment by Robinlovelace** [comment]
I mean when we write the dataframe back to 1 line per attribute-event pair. I think when it's in an ical object it's worth having a few extra columns with lots of NAs to ensure the data is '[tidy](http://vita.had.co.nz/papers/tidy-data.html)'.

Unless there is an alternative for timestrings. Another option is to not support I/O round trips involving different timezones. I don't really like that option. Any others? All food for the minihack.

**Comment by layik** [comment]
Option 3 is not possible in the world of dataframes. Looking for alternatives.

**Comment by layik** [comment]
Considering the "NA" option :)

**Comment by Robinlovelace** [comment]
Just realised I didn't answer your questions from before. Preliminary answers:

> do all VEVENTS in a VCALENDAR are all in the same TZID?

Seeming not. I think TZIDs are in the spec. It seems they can be specified for the entire calendar (we should support this) and for individual events. Rare enough to justify a new column full of NAs for each one? I think so.

> should/must all VEVENTS have the same properties?

In the `tibble` in the `ical` object: yes. In the output from `ic_write()`: no.

**Comment by layik** [comment]
![screenshot from 2018-09-25 20-48-37](https://user-images.githubusercontent.com/408568/46039013-829a9980-c104-11e8-9594-17d70b5e76d0.png)

**Comment by layik** [comment]
Really tricky!

**Comment by Robinlovelace** [comment]
I think as long as it's semantically the same is fine.

**Comment by Robinlovelace** [comment]
Happy :+1:
